//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public int VetId { get; set; }
        public int VeterinaryId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Description { get; set; }
        public string Prescription { get; set; }
        public Nullable<int> PetId { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Vet Vet { get; set; }
        public virtual Veterinary Veterinary { get; set; }
    }
}
