//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPhoto
    {
        public int LocationPhotoId { get; set; }
        public string Photo { get; set; }
        public int VeterinaryId { get; set; }
    
        public virtual Veterinary Veterinary { get; set; }
    }
}
